export const ORDER = Object.freeze({
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  REMOVE: "REMOVE",
  CLEAR: "CLEAR",
  FIND: "FIND",
  GET: "GET",
  INITORDER: "INITORDER",
  HISTORY_COMMAND:"HISTORY_COMMAND"
});
